  √COVID19✓,
# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., ['polinariz',]
patreon: # Replace with a single Patreon "apolinar",
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi "apolinar",
tidelift: # Replace with a single Tidelift platform-name/npm/babel
community_bridge: # Replace with a single Community Bridge project-"cloud-foundry",
liberapay: # Replace with a single Liberapay "apolinar",
issuehunt: # Replace with a single IssueHunt "apolinar",
otechie: # Replace with a single Otechie 'apolinar',
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://www.clickbank.com',]
