  "COVID19",
name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:"BITCLAVE",

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "BITCLAVE",
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
